() => { const sql = `-- =====================================================================
-- YARZ Supabase â€” Combined migration script (PHASE 2)
-- Date: 2026-06-20
-- Generated by Kilo
--
-- HOW TO USE:
--   1. Login to https://supabase.com/dashboard in YOUR OWN Chrome
--   2. Open/create your project (e.g. yarz-production)
--   3. Left sidebar: SQL Editor â†’ New query
--   4. Paste this ENTIRE file (or load from disk)
--   5. Click RUN. Wait ~30 sec.
--   6. Verify: Table Editor shows inventory, orders, website_orders, ...
--
-- EXPECTED RESULT:
--   22 tables + 5 views + 17 RPCs + 21 RLS policies + 4 RLS-enabled tables
-- =====================================================================


-- =====================================================================
-- >>> schema.sql
-- =====================================================================

-- =====================================================================
-- YARZ Supabase Schema (PostgreSQL)
-- Date: 2026-06-20
-- Migrates 16 Google Sheets tabs into proper relational tables.
-- Money columns are NUMERIC(12,2) -- NOT FLOAT -- to avoid rounding bugs.
-- Stock counts are INTEGER; formulas become GENERATED columns.
-- All tables have id BIGSERIAL PK + created_at/updated_at TIMESTAMPTZ.
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- 1. INVENTORY (52 columns from Google Sheets INVENTORY tab)
-- ---------------------------------------------------------------------
create table if not exists inventory (
  id                  bigserial primary key,
  product             text not null unique,
  image_1             text default '''',
  image_2             text default '''',
  image_3             text default '''',
  video_url           text default '''',
  description         text default '''',
  category            text default '''',
  fabric              text default '''',
  badge               text default '''',
  size_chart          text default '''',
  delivery_days       text default '''',
  cost                numeric(12,2) default 0,
  regular             numeric(12,2) default 0,
  sale                numeric(12,2) default 0,
  disc_percent        numeric(5,2) default 0,
  disc_type           text default ''Normal'',
  dhaka_delivery      numeric(12,2) default 60,
  outside_delivery    numeric(12,2) default 120,
  stk_s               integer default 0,
  stk_m               integer default 0,
  stk_l               integer default 0,
  stk_xl              integer default 0,
  stk_xxl             integer default 0,
  stk_3xl             integer default 0,
  sold_s              integer default 0,
  sold_m              integer default 0,
  sold_l              integer default 0,
  sold_xl             integer default 0,
  sold_xxl            integer default 0,
  sold_3xl            integer default 0,
  -- GENERATED computed columns (was Sheet formulas col 27,29,30)
  tot_sold            integer generated always as
                       (coalesce(sold_s,0)+coalesce(sold_m,0)+coalesce(sold_l,0)
                        +coalesce(sold_xl,0)+coalesce(sold_xxl,0)+coalesce(sold_3xl,0)) stored,
  tot_stock           integer generated always as
                       (coalesce(stk_s,0)+coalesce(stk_m,0)+coalesce(stk_l,0)
                        +coalesce(stk_xl,0)+coalesce(stk_xxl,0)+coalesce(stk_3xl,0)) stored,
  remaining           integer generated always as
                       (tot_stock - tot_sold) stored,
  returns             integer default 0,
  invest              numeric(12,2) default 0,
  revenue             numeric(12,2) default 0,
  to_recover          numeric(12,2) default 0,
  gross               numeric(12,2) default 0,
  fb_ad               numeric(12,2) default 0,
  net                 numeric(12,2) default 0,
  disc_impact         numeric(12,2) default 0,
  updated_at          timestamptz default now(),
  status              text default ''Active'' check (status in (''Active'',''Draft'',''Archived'')),
  image_4             text default '''',
  image_5             text default '''',
  image_6             text default '''',
  coupon_active       text default ''No'' check (coupon_active in (''Yes'',''No'',''Hidden'')),
  coupon_code         text default '''',
  coupon_disc_percent numeric(5,2) default 0,
  hidden_sizes        text default '''',
  size_type           text default '''',
  accessory           text default ''No'' check (accessory in (''Yes'',''No'')),
  created_at          timestamptz default now()
);
create index if not exists idx_inventory_status on inventory(status);
create index if not exists idx_inventory_category on inventory(category);
create index if not exists idx_inventory_updated on inventory(updated_at desc);

-- ---------------------------------------------------------------------
-- 2. ORDERS (16 columns, manual / phone orders)
-- ---------------------------------------------------------------------
create table if not exists orders (
  id              bigserial primary key,
  order_id        text unique,
  date            timestamptz default now(),
  cust_name       text default '''',
  cust_phone      text default '''',
  cust_addr       text default '''',
  deliv_dist      text default '''',
  deliv_zone      text default '''',
  product         text default '''',
  size            text default '''',
  qty             integer default 1,
  price           numeric(12,2) default 0,
  delivery_charge numeric(12,2) default 0,
  total           numeric(12,2) default 0,
  payment         text default ''Cash on Delivery'',
  status          text default ''Pending'' check (status in
                    (''Pending'',''Confirmed'',''Processing'',''Shipped'',
                     ''Delivered'',''Cancelled'',''Returned'')),
  courier         text default '''',
  notes           text default '''',
  created_at      timestamptz default now()
);
create index if not exists idx_orders_phone on orders(cust_phone);
create index if not exists idx_orders_status on orders(status);
create index if not exists idx_orders_date on orders(date desc);

-- ---------------------------------------------------------------------
-- 3. WEBSITE_ORDERS (29 columns from Website_Orders tab)
--    Includes fraud signals (device_id, ip, country, asn, risk_score...)
-- ---------------------------------------------------------------------
create table if not exists website_orders (
  id              bigserial primary key,
  order_id        text unique,
  date            timestamptz default now(),
  cust_name       text default '''',
  cust_phone      text default '''',
  cust_addr       text default '''',
  deliv_zone      text default '''',
  product         text default '''',
  size            text default '''',
  qty             integer default 1,
  price           numeric(12,2) default 0,
  delivery_charge numeric(12,2) default 0,
  total           numeric(12,2) default 0,
  payment         text default ''Cash on Delivery'',
  notes           text default '''',
  coupon_code     text default '''',
  status          text default ''Pending'' check (status in
                    (''Pending'',''Confirmed'',''Processing'',''Picked Up'',
                     ''Ready for Delivery'',''Handed to Courier'',''In Transit'',
                     ''Shipped'',''Delivered'',''Cancelled'',''Returned'')),
  courier         text default '''',
  updated_at      timestamptz default now(),
  activity        text default '''',
  device_id       text default '''',
  ip              text default '''',
  country         text default '''',
  asn             text default '''',
  risk_score      numeric(5,2) default 0,
  risk_signals    text default '''',
  flagged         boolean default false,
  flag_reason     text default '''',
  flagged_at      timestamptz,
  flagged_by      text default '''',
  created_at      timestamptz default now()
);
create index if not exists idx_wo_phone on website_orders(cust_phone);
create index if not exists idx_wo_status on website_orders(status);
create index if not exists idx_wo_date on website_orders(date desc);
create index if not exists idx_wo_flagged on website_orders(flagged) where flagged = true;
create index if not exists idx_wo_device on website_orders(device_id);

-- ---------------------------------------------------------------------
-- 4. TRANSACTIONS (8 columns)
-- ---------------------------------------------------------------------
create table if not exists transactions (
  id             bigserial primary key,
  date           timestamptz default now(),
  product        text default '''',
  type           text default ''Sale'' check (type in (''Sale'',''Return'',''Adjustment'')),
  size           text default '''',
  qty            integer default 0,
  revenue        numeric(12,2) default 0,
  cost           numeric(12,2) default 0,
  profit         numeric(12,2) generated always as (revenue - cost) stored,
  created_at     timestamptz default now()
);
create index if not exists idx_tx_date on transactions(date desc);
create index if not exists idx_tx_product on transactions(product);

-- ---------------------------------------------------------------------
-- 5. AD_TRACKER (7 columns)
-- ---------------------------------------------------------------------
create table if not exists ad_tracker (
  id          bigserial primary key,
  date        timestamptz default now(),
  product     text default '''',
  spend       numeric(12,2) default 0,
  reach       integer default 0,
  impressions integer default 0,
  clicks      integer default 0,
  notes       text default '''',
  created_at  timestamptz default now()
);
create index if not exists idx_ad_date on ad_tracker(date desc);

-- ---------------------------------------------------------------------
-- 6. EXPENSES (5 columns)
-- ---------------------------------------------------------------------
create table if not exists expenses (
  id          bigserial primary key,
  date        timestamptz default now(),
  category    text default '''',
  description text default '''',
  amount      numeric(12,2) default 0,
  notes       text default '''',
  created_at  timestamptz default now()
);
create index if not exists idx_exp_date on expenses(date desc);
create index if not exists idx_exp_category on expenses(category);

-- ---------------------------------------------------------------------
-- 7. MONTHLY_REPORT (6 columns)
-- ---------------------------------------------------------------------
create table if not exists monthly_reports (
  id          bigserial primary key,
  month       text unique, -- format YYYY-MM
  revenue     numeric(12,2) default 0,
  cost        numeric(12,2) default 0,
  ad_spend    numeric(12,2) default 0,
  net_profit  numeric(12,2) generated always as (revenue - cost - ad_spend) stored,
  orders      integer default 0,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- ---------------------------------------------------------------------
-- 8. YEARLY_REPORT (6 columns)
-- ---------------------------------------------------------------------
create table if not exists yearly_reports (
  id          bigserial primary key,
  year        integer unique,
  revenue     numeric(12,2) default 0,
  cost        numeric(12,2) default 0,
  ad_spend    numeric(12,2) default 0,
  net_profit  numeric(12,2) generated always as (revenue - cost - ad_spend) stored,
  orders      integer default 0,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- ---------------------------------------------------------------------
-- 9. SETTINGS (key-value store)
-- ---------------------------------------------------------------------
create table if not exists settings (
  id          bigserial primary key,
  key         text unique not null,
  value       text default '''',
  description text default '''',
  is_secret   boolean default false,
  updated_at  timestamptz default now()
);
create index if not exists idx_settings_key on settings(key);

-- ---------------------------------------------------------------------
-- 10. DELIVERY_CHARGES (4 columns)
-- ---------------------------------------------------------------------
create table if not exists delivery_charges (
  id        text primary key,    -- e.g. inside_narayanganj
  name      text not null,
  charge    numeric(12,2) default 0,
  active    boolean default true,
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ---------------------------------------------------------------------
-- 11. CUSTOMERS (LTV aggregation; derived from website_orders + orders)
-- ---------------------------------------------------------------------
create table if not exists customers (
  id              bigserial primary key,
  phone           text unique not null,
  name            text default '''',
  total_orders    integer default 0,
  total_spent     numeric(12,2) default 0,
  first_order_at  timestamptz,
  last_order_at   timestamptz,
  risk_score      numeric(5,2) default 0,
  is_blocked      boolean default false,
  block_reason    text default '''',
  notes           text default '''',
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);
create index if not exists idx_customers_phone on customers(phone);
create index if not exists idx_customers_blocked on customers(is_blocked) where is_blocked = true;

-- ---------------------------------------------------------------------
-- 12. _ACTIVITY (4 columns)
-- ---------------------------------------------------------------------
create table if not exists _activity (
  id          bigserial primary key,
  ts          timestamptz default now(),
  product     text default '''',
  old_status  text default '''',
  new_status  text default '''',
  actor       text default ''system''
);
create index if not exists idx_activity_ts on _activity(ts desc);
create index if not exists idx_activity_product on _activity(product);

-- ---------------------------------------------------------------------
-- 13. _DRAFT_DATA / _ARCHIVE_DATA (2 cols each)
-- ---------------------------------------------------------------------
create table if not exists _draft_data (
  id    bigserial primary key,
  name  text unique,
  note  text default '''',
  created_at timestamptz default now()
);
create table if not exists _archive_data (
  id    bigserial primary key,
  name  text unique,
  note  text default '''',
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------
-- 14. ADMIN_SESSIONS + ADMIN_LOGIN_ATTEMPTS (auth)
-- ---------------------------------------------------------------------
create table if not exists admin_sessions (
  id          bigserial primary key,
  token       text unique not null,
  username    text not null,
  user_agent  text default '''',
  ip          text default '''',
  expires_at  timestamptz not null,
  created_at  timestamptz default now(),
  last_used_at timestamptz default now()
);
create index if not exists idx_sessions_token on admin_sessions(token);
create index if not exists idx_sessions_expires on admin_sessions(expires_at);

create table if not exists admin_login_attempts (
  id          bigserial primary key,
  username    text default '''',
  ip          text default '''',
  success     boolean default false,
  user_agent  text default '''',
  ts          timestamptz default now()
);
create index if not exists idx_login_ip_ts on admin_login_attempts(ip, ts desc);
create index if not exists idx_login_success on admin_login_attempts(success, ts desc);

-- ---------------------------------------------------------------------
-- 15. STEADFAST_CACHE (avoid hitting Steadfast every load)
-- ---------------------------------------------------------------------
create table if not exists steadfast_keys (
  id          integer primary key default 1,
  api_key     text default '''',
  secret_key  text default '''',
  updated_at  timestamptz default now(),
  check constraint only_one_row check (id = 1)
);

create table if not exists steadfast_balance_cache (
  id          integer primary key default 1,
  balance     numeric(12,2) default 0,
  raw_json    jsonb,
  fetched_at  timestamptz default now(),
  check constraint only_one_row_sb check (id = 1)
);

-- ---------------------------------------------------------------------
-- 16. NEWSLETTER subscribers (from _webSubscribeNewsletter)
-- ---------------------------------------------------------------------
create table if not exists newsletter_subscribers (
  id          bigserial primary key,
  email       text unique,
  phone       text,
  source      text default ''website'',
  subscribed_at timestamptz default now()
);

-- ---------------------------------------------------------------------
-- 17. RATE_LIMIT_LOG (replaces GAS PropertiesService sliding window)
-- ---------------------------------------------------------------------
create table if not exists rate_limit_log (
  id          bigserial primary key,
  scope       text not null,   -- e.g. ''api'', ''place_order''
  identifier  text not null,   -- ip or phone
  ts          timestamptz default now()
);
create index if not exists idx_rl_scope_id_ts on rate_limit_log(scope, identifier, ts desc);

-- ---------------------------------------------------------------------
-- 18. AUDIT_LOG (track every admin destructive action)
-- ---------------------------------------------------------------------
create table if not exists audit_log (
  id          bigserial primary key,
  action      text not null,
  actor       text default ''admin'',
  details     jsonb,
  ts          timestamptz default now()
);
create index if not exists idx_audit_action_ts on audit_log(action, ts desc);

-- =====================================================================
-- END schema.sql
-- =====================================================================


-- =====================================================================
-- >>> views.sql
-- =====================================================================

-- =====================================================================
-- YARZ Supabase Views (replaces Google Sheets FILTER formulas)
-- Date: 2026-06-20
-- These views mirror the GAS DRAFT_VIEW, ARCHIVE_VIEW, WEBSITE_SYNC
-- so the existing _doSheetRead(range) API can be reproduced.
-- =====================================================================

-- WEBSITE_SYNC view (Active products, customer-facing subset of columns)
create or replace view website_sync_view as
select
  product         as "Product",
  image_1         as "Image1",
  image_2         as "Image2",
  image_3         as "Image3",
  video_url       as "Video",
  description     as "Description",
  category        as "Category",
  fabric          as "Fabric",
  badge           as "Badge",
  size_chart      as "SizeChart",
  delivery_days   as "DeliveryDays",
  regular         as "Regular",
  sale            as "Sale",
  disc_percent    as "Disc%",
  disc_type       as "DiscType",
  dhaka_delivery  as "Delivery(Dhaka)",
  outside_delivery as "Delivery(Outside)",
  greatest(stk_s - sold_s, 0) as "S_Left",
  greatest(stk_m - sold_m, 0) as "M_Left",
  greatest(stk_l - sold_l, 0) as "L_Left",
  greatest(stk_xl - sold_xl, 0) as "XL_Left",
  greatest(stk_xxl - sold_xxl, 0) as "XXL_Left",
  greatest(stk_3xl - sold_3xl, 0) as "3XL_Left",
  status          as "Status",
  image_4         as "Image4",
  image_5         as "Image5",
  image_6         as "Image6",
  coupon_active   as "CouponActive",
  coupon_code     as "CouponCode",
  coupon_disc_percent as "CouponDisc"
from inventory
where status = ''Active'' and product <> '''';

-- DRAFT_VIEW (Draft products only, admin sees)
create or replace view inventory_draft_view as
select
  row_number() over (order by product) as "#",
  product         as "Product",
  image_1         as "Image",
  category        as "Category",
  fabric          as "Fabric",
  badge           as "Badge",
  cost            as "Cost",
  regular         as "Regular",
  sale            as "Sale",
  tot_stock       as "Stock",
  tot_sold        as "Sold",
  remaining       as "Left",
  ''--''          as "Action"
from inventory
where status = ''Draft'' and product <> '''';

-- ARCHIVE_VIEW (Archived products only)
create or replace view inventory_archive_view as
select
  row_number() over (order by product) as "#",
  product         as "Product",
  image_1         as "Image",
  category        as "Category",
  fabric          as "Fabric",
  badge           as "Badge",
  cost            as "Cost",
  regular         as "Regular",
  sale            as "Sale",
  tot_stock       as "Stock",
  tot_sold        as "Sold",
  remaining       as "Left",
  ''--''          as "Action"
from inventory
where status = ''Archived'' and product <> '''';

-- PUBLIC_PRODUCTS view (used by frontend; subset of WEBSITE_SYNC + computed flags)
create or replace view public_products as
select *
from website_sync_view;

-- CUSTOMER_LTV view (aggregates orders + website_orders)
create or replace view customer_ltv_view as
select
  cust_phone as phone,
  max(cust_name) as name,
  count(*) as total_orders,
  coalesce(sum(total), 0) as total_spent,
  min(date) as first_order_at,
  max(date) as last_order_at
from (
  select cust_name, cust_phone, total, date from orders where cust_phone <> ''''
  union all
  select cust_name, cust_phone, total, date from website_orders where cust_phone <> ''''
) combined
group by cust_phone;

-- =====================================================================
-- END views.sql
-- =====================================================================


-- =====================================================================
-- >>> rls.sql
-- =====================================================================

-- =====================================================================
-- YARZ Supabase Row Level Security
-- Date: 2026-06-20
-- Strategy:
--   1. anon role  -> SELECT on read-only tables + INSERT on website_orders/newsletter
--   2. authenticated -> full CRUD (admin only)
-- We do NOT use Supabase Auth for admin (custom session table used instead).
--   The Worker will set service_role key for ALL writes.
-- =====================================================================

-- Enable RLS on every table
alter table inventory             enable row level security;
alter table orders                enable row level security;
alter table website_orders        enable row level security;
alter table transactions          enable row level security;
alter table ad_tracker            enable row level security;
alter table expenses              enable row level security;
alter table monthly_reports       enable row level security;
alter table yearly_reports        enable row level security;
alter table settings              enable row level security;
alter table delivery_charges      enable row level security;
alter table customers             enable row level security;
alter table _activity             enable row level security;
alter table _draft_data           enable row level security;
alter table _archive_data         enable row level security;
alter table admin_sessions        enable row level security;
alter table admin_login_attempts  enable row level security;
alter table steadfast_keys        enable row level security;
alter table steadfast_balance_cache enable row level security;
alter table newsletter_subscribers enable row level security;
alter table rate_limit_log        enable row level security;
alter table audit_log             enable row level security;

-- ---------------------------------------------------------------------
-- PUBLIC READS (anon role can SELECT the data website needs to render)
-- ---------------------------------------------------------------------
create policy "anon read active inventory" on inventory
  for select to anon using (status = ''Active'');

create policy "anon read delivery_charges" on delivery_charges
  for select to anon using (active = true);

create policy "anon read public settings" on settings
  for select to anon using (is_secret = false);

-- ---------------------------------------------------------------------
-- PUBLIC WRITES (place order, subscribe newsletter)
-- ---------------------------------------------------------------------
create policy "anon insert website_orders" on website_orders
  for insert to anon with check (true);

create policy "anon insert newsletter" on newsletter_subscribers
  for insert to anon with check (true);

-- ---------------------------------------------------------------------
-- ALL OTHER ACCESS -> requires service_role key (Worker uses this)
-- Admin Panel NEVER talks to Supabase directly; Worker proxies with
-- service_role after verifying session token from admin_sessions.
-- ---------------------------------------------------------------------
-- (No policies = no access for anon/authenticated = fail-closed default)


-- =====================================================================
-- >>> rpc.sql
-- =====================================================================

-- =====================================================================
-- YARZ Supabase RPC functions (Postgres-side business logic)
-- Date: 2026-06-20
-- These are called by supabase-adapter-v2.js.
-- Security: ALL functions check admin session EXCEPT admin_login.
-- =====================================================================

-- ---------------------------------------------------------------------
-- admin_login: verify username/password, create session, return token
-- ---------------------------------------------------------------------
create or replace function admin_login(
  p_username text, p_password text, p_user_agent text default ''''
)
returns table (token text, username text, expires_at timestamptz)
language plpgsql security definer as $$
declare
  v_user_id bigint;
  v_hash text;
  v_token text;
  v_expires timestamptz;
begin
  -- Find user (simple lookup; production should use admin_users table)
  select u.id, u.password_hash into v_user_id, v_hash
  from admin_users u where u.username = p_username and u.is_active = true;
  if v_user_id is null then
    insert into admin_login_attempts(username, success, user_agent) values (p_username, false, p_user_agent);
    return;
  end if;
  -- Verify hash (uses pgcrypto crypt())
  if v_hash != crypt(p_password, v_hash) then
    insert into admin_login_attempts(username, success, user_agent) values (p_username, false, p_user_agent);
    return;
  end if;
  -- Issue token
  v_token := encode(gen_random_bytes(32), ''hex'');
  v_expires := now() + interval ''7 days'';
  insert into admin_sessions(token, username, user_agent, expires_at)
    values (v_token, p_username, p_user_agent, v_expires);
  insert into admin_login_attempts(username, success, user_agent) values (p_username, true, p_user_agent);
  return query select v_token, p_username, v_expires;
end $$;

-- ---------------------------------------------------------------------
-- admin_logout: invalidate session
-- ---------------------------------------------------------------------
create or replace function admin_logout(p_token text)
returns boolean language plpgsql security definer as $$
begin
  delete from admin_sessions where token = p_token;
  return true;
end $$;

-- ---------------------------------------------------------------------
-- verify_session: returns true if session is valid (not expired)
-- ---------------------------------------------------------------------
create or replace function verify_session(p_token text)
returns boolean language plpgsql security definer as $$
declare
  v_ok boolean;
begin
  update admin_sessions set last_used_at = now()
    where token = p_token and expires_at > now();
  v_ok := found;
  if not v_ok then
    -- Clean up expired sessions occasionally
    delete from admin_sessions where expires_at < now() - interval ''1 day'';
  end if;
  return v_ok;
end $$;

-- ---------------------------------------------------------------------
-- check_login_rate_limit: returns false if too many failed attempts
-- ---------------------------------------------------------------------
create or replace function check_login_rate_limit(p_ip text, p_window_sec integer)
returns boolean language plpgsql security definer as $$
declare
  v_count int;
begin
  select count(*) into v_count from admin_login_attempts
    where ts > now() - (p_window_sec || '' seconds'')::interval and success = false;
  return v_count < 20;
end $$;

-- ---------------------------------------------------------------------
-- full_factory_reset: deletes ALL business data (preserves auth + logs)
-- ---------------------------------------------------------------------
create or replace function full_factory_reset()
returns void language plpgsql security definer as $$
begin
  truncate table website_orders, orders, transactions, ad_tracker, expenses,
    monthly_reports, yearly_reports, customers, _activity, _draft_data, _archive_data
    restart identity cascade;
  delete from inventory;
  insert into audit_log(action, details) values (''full_factory_reset'', jsonb_build_object(''ts'', now()));
end $$;

-- ---------------------------------------------------------------------
-- clear_financials_only
-- ---------------------------------------------------------------------
create or replace function clear_financials_only()
returns void language plpgsql security definer as $$
begin
  truncate table website_orders, orders, transactions, ad_tracker, expenses,
    monthly_reports, yearly_reports
    restart identity cascade;
  insert into audit_log(action, details) values (''clear_financials_only'', jsonb_build_object(''ts'', now()));
end $$;

-- ---------------------------------------------------------------------
-- clear_inventory_only
-- ---------------------------------------------------------------------
create or replace function clear_inventory_only()
returns void language plpgsql security definer as $$
begin
  truncate table inventory restart identity cascade;
  insert into audit_log(action, details) values (''clear_inventory_only'', jsonb_build_object(''ts'', now()));
end $$;

-- ---------------------------------------------------------------------
-- atomic_adjust_stock: race-condition-safe stock update
-- Returns false if not enough stock for sale.
-- ---------------------------------------------------------------------
create or replace function atomic_adjust_stock(
  p_product text, p_size text, p_delta integer, p_kind text
)
returns boolean language plpgsql security definer as $$
declare
  v_stk_col text; v_sold_col text;
  v_cur integer;
begin
  v_stk_col  := case p_size when ''S'' then ''stk_s'' when ''M'' then ''stk_m''
                              when ''L'' then ''stk_l'' when ''XL'' then ''stk_xl''
                              when ''XXL'' then ''stk_xxl'' when ''3XL'' then ''stk_3xl'' end;
  v_sold_col := replace(v_stk_col, ''stk_'', ''sold_'');
  if v_stk_col is null then raise exception ''Unknown size: %'', p_size; end if;

  execute format(''select %I from inventory where product = $1 for update'', v_stk_col)
    into v_cur using p_product;

  if p_kind = ''sale'' and v_cur < p_delta then return false; end if;

  execute format(''update inventory set %I = %I - $1, %I = %I + $1, updated_at = now() where product = $2'',
    v_stk_col, v_stk_col, v_sold_col, v_sold_col)
    using p_delta, p_product;
  return true;
end $$;

-- ---------------------------------------------------------------------
-- update_customer_ltv: refresh customer aggregates from orders
-- ---------------------------------------------------------------------
create or replace function update_customer_ltv()
returns void language sql security definer as $$
  insert into customers (phone, name, total_orders, total_spent, first_order_at, last_order_at)
  select phone, max(name), count(*), coalesce(sum(total),0), min(first_order_at), max(last_order_at)
  from customer_ltv_view
  group by phone
  on conflict (phone) do update set
    name = excluded.name,
    total_orders = excluded.total_orders,
    total_spent = excluded.total_spent,
    first_order_at = excluded.first_order_at,
    last_order_at = excluded.last_order_at,
    updated_at = now();
$$;

-- =====================================================================
-- admin_users seed (create your admin here)
-- =====================================================================
create table if not exists admin_users (
  id              bigserial primary key,
  username        text unique not null,
  password_hash   text not null,    -- bcrypt-style; use crypt() to set
  is_active       boolean default true,
  created_at      timestamptz default now(),
  last_login_at   timestamptz
);

-- Seed: username=maruf_ix, password=Hassan__00
-- (Default password; CHANGE IMMEDIATELY after first login)
insert into admin_users (username, password_hash)
values (''maruf_ix'', crypt(''Hassan__00'', gen_salt(''bf'', 10)))
on conflict (username) do update set password_hash = excluded.password_hash;

-- =====================================================================
-- END rpc.sql
-- =====================================================================


-- =====================================================================
-- >>> seed_defaults.sql
-- =====================================================================

-- =====================================================================
-- YARZ Supabase Seed Defaults
-- Date: 2026-06-20
-- Populates: settings (defaults from _setupSettings), delivery_charges
-- =====================================================================

insert into settings (key, value, description) values
  (''Store Name'',          ''YARZ'',                                 ''sotorer nam''),
  (''Store Phone'',         '''',                                     ''phone number''),
  (''Store Email'',         '''',                                     ''email''),
  (''Store Address'',       '''',                                     ''thikana''),
  (''Currency Symbol'',     ''?'',                                    ''currency''),
  (''Link Facebook'',       ''https://www.facebook.com/Yarzbd'',      ''Footer/contact social link''),
  (''Link Instagram'',      ''https://www.instagram.com/yarz_bd'',    ''Footer/contact social link''),
  (''Link WhatsApp'',       ''https://wa.me/8801601743670'',          ''Footer/contact social link''),
  (''Link Messenger'',      ''https://m.me/Yarzbd'',                  ''Footer/contact social link + floating chat''),
  (''Link TikTok'',         ''https://tiktok.com/@yarzbd'',           ''Footer/contact social link''),
  (''Link YouTube'',        '''',                                     ''Optional footer/contact social link''),
  (''Custom Categories'',   ''Shirt,T-Shirt,Polo,Formal,Casual,Panjabi,Kurta,Pant,Formal Pant,Jeans,Chinos,Cargo Pant,Trouser,Hoodie,Sweater,Jacket,Blazer,Coat,Waistcoat,Tracksuit,Shorts,Three Quarter,Shoes,Sneakers,Sandals,Belt,Cap,Hat,Watch,Wallet,Sunglasses,Accessories,Other'', ''comma-separated''),
  (''Custom Fabrics'',      ''Oxford Cotton,Poplin Cotton,Premium Cotton,Cotton,China Fabric,Twill Cotton,Linen,Silk,Denim,Polyester,Rayon,Viscose,Chiffon,Georgette,Khadi,Jersey,Fleece,Wool,Corduroy,Satin,Velvet,Nylon,Spandex,Mixed,Other'', ''comma-separated''),
  (''Custom Badges'',       '',New Arrival,Hot Sale,Best Seller,Limited Edition,Trending,Premium,Sold Out Soon'', ''comma-separated''),
  (''GitHub Token'',        '''',                                     ''GitHub sync''),
  (''GitHub Repo'',         '''',                                     ''GitHub sync''),
  (''GitHub Branch'',       ''main'',                                 ''GitHub sync''),
  (''GitHub Path'',         ''data.json'',                            ''GitHub sync'')
on conflict (key) do nothing;

insert into delivery_charges (id, name, charge, active, sort_order) values
  (''inside_narayanganj'',  ''Inside Narayanganj'',  70,  true, 1),
  (''outside_narayanganj'', ''Outside Narayanganj'', 140, true, 2)
on conflict (id) do nothing;

-- Mark the secret keys as secret so they do NOT leak via anon reads
update settings set is_secret = true where key in (''GitHub Token'',''Steadfast API Key'',''Steadfast Secret Key'');


-- =====================================================================
-- >>> fortress_steadfast_supplement.sql
-- =====================================================================

-- =====================================================================
-- YARZ Supabase Supplement Ã¢â‚¬â€ Fortress + Steadfast + Reports
-- Date: 2026-06-20
-- Run AFTER schema.sql + views.sql + rls.sql + rpc.sql + seed_defaults.sql
-- This adds the 3 missing tables and 8 missing RPCs identified in
-- analysis/gaps.md.
--
-- Tables added (3):
--   blocked_devices       -- Fortress device blocklist
--   fortress_log          -- Fortress event audit log
--   steadfast_consignments -- All Steadfast consignments created
--
-- RPCs added (8):
--   record_return             -- atomic SOLD_* decrement + Return marker
--   delete_website_order      -- full reversal (cancel tx + restore stock)
--   generate_monthly_report   -- aggregate orders/website_orders/tx/ads
--   steadfast_create_consignment -- call Steadfast API + log + update status
--   fortress_block            -- upsert into blocked_devices
--   fortress_unblock          -- delete from blocked_devices
--   fortress_log_event        -- insert into fortress_log
--   fortress_lookup           -- return all blocked + recent log
-- =====================================================================

-- ---------------------------------------------------------------------
-- blocked_devices
-- ---------------------------------------------------------------------
create table if not exists blocked_devices (
  id              bigserial primary key,
  device_id       text unique not null,
  blocked_at      timestamptz default now(),
  blocked_by      text default 'admin',
  block_reason    text default 'manual',
  block_type      text default 'hard',  -- 'hard' | 'soft' | 'shadow'
  expires_at      timestamptz,
  admin_notes     text,
  status          text default 'active', -- 'active' | 'archived'
  last_seen       timestamptz,
  order_attempts  int default 0,
  risk_score      int default 0,
  phones_seen     text,                  -- comma-separated
  ips_seen        text,                  -- comma-separated
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);
create index if not exists idx_blocked_devices_status on blocked_devices(status) where status = 'active';
create index if not exists idx_blocked_devices_expires on blocked_devices(expires_at) where expires_at is not null;

alter table blocked_devices enable row level security;

-- ---------------------------------------------------------------------
-- fortress_log
-- ---------------------------------------------------------------------
create table if not exists fortress_log (
  id              bigserial primary key,
  log_id          text unique not null,  -- "FL-YYYYMMDD-HHMMSS-XXXXXX"
  ts              timestamptz default now(),
  event_type      text not null,         -- 'block_added' | 'block_removed' | 'shadow_ban' | 'burst_attempt' etc.
  device_id       text,
  phone_hash      text,                  -- FNV-1a hash, not raw
  ip              text,
  country         text,
  risk_score      int default 0,
  reason          text,
  actor           text default 'auto',   -- 'admin' | 'auto'
  order_id        text,
  notes           text
);
create index if not exists idx_fortress_log_ts on fortress_log(ts desc);
create index if not exists idx_fortress_log_device on fortress_log(device_id);
create index if not exists idx_fortress_log_event on fortress_log(event_type, ts desc);

alter table fortress_log enable row level security;

-- ---------------------------------------------------------------------
-- steadfast_consignments (audit log of all Steadfast API calls)
-- ---------------------------------------------------------------------
create table if not exists steadfast_consignments (
  id                 bigserial primary key,
  consignment_id     text unique,                    -- Steadfast consignment_id
  tracking_code      text,
  invoice            text not null,                  -- YARZ order_id
  recipient_name     text,
  recipient_phone    text,
  recipient_address  text,
  cod_amount         numeric(12,2) default 0,
  total_lot          int default 0,
  item_description   text,
  note               text,
  delivery_type      int default 0,                  -- 0=home, 1=hub
  status             text default 'pending',         -- 'pending' | 'in_review' | 'delivered' | 'cancelled' | 'returned'
  stead_response     jsonb,                          -- raw response from Steadfast
  created_at         timestamptz default now(),
  last_checked_at    timestamptz,
  delivered_at       timestamptz,
  cancelled_at       timestamptz
);
create index if not exists idx_steadfast_inv on steadfast_consignments(invoice);
create index if not exists idx_steadfast_track on steadfast_consignments(tracking_code);
create index if not exists idx_steadfast_status on steadfast_consignments(status, created_at desc);

alter table steadfast_consignments enable row level security;

-- =====================================================================
-- RPCs
-- =====================================================================

-- ---------------------------------------------------------------------
-- record_return: atomic SOLD_* decrement + TRANSACTIONS Return marker
-- (Mirrors saveReturnFromForm in GAS line 2026-2142)
-- ---------------------------------------------------------------------
create or replace function record_return(
  p_product text, p_size text, p_qty int, p_user text default 'admin'
)
returns boolean language plpgsql security definer as $$
declare
  v_sold_col text;
  v_cur int;
  v_new int;
begin
  v_sold_col := case upper(p_size)
    when 'S'   then 'sold_s'   when 'M'   then 'sold_m'
    when 'L'   then 'sold_l'   when 'XL'  then 'sold_xl'
    when 'XXL' then 'sold_xxl' when '3XL' then 'sold_3xl'
    when 'ONE' then 'sold_m'   else null end;
  if v_sold_col is null then raise exception 'Unknown size: %', p_size; end if;

  -- Lock inventory row
  execute format('select %I from inventory where product = $1 for update', v_sold_col)
    into v_cur using p_product;

  v_new := greatest(0, coalesce(v_cur, 0) - p_qty);
  execute format('update inventory set %I = $1, updated_at = now() where product = $2',
    v_sold_col) using v_new, p_product;

  -- Log Return marker (qty=0 per v15.32 fix to keep AB=0 source-of-truth)
  insert into transactions (date, product, type, size, qty, revenue, cost, profit)
  values (now(), p_product, 'Return', p_size, 0, 0, 0, 0);

  insert into audit_log (action, actor, details)
  values ('record_return', p_user,
    jsonb_build_object('product', p_product, 'size', p_size, 'qty', p_qty, 'new_stock', v_new));
  return true;
end $$;

-- ---------------------------------------------------------------------
-- delete_website_order: full reversal (cancel TRANSACTIONS, restore SOLD_*, delete rows)
-- (Mirrors _webDeleteWebsiteOrder in GAS line 3099-3226)
-- ---------------------------------------------------------------------
create or replace function delete_website_order(
  p_order_id text, p_user text default 'admin'
)
returns table (rows_deleted int, stock_restored int) language plpgsql security definer as $$
declare
  v_item record;
  v_sold_col text;
  v_remaining int;
  v_rows int := 0;
  v_stock int := 0;
begin
  -- Snapshot order items before deleting
  for v_item in
    select cust_phone, product, size, qty, status
    from website_orders where order_id = p_order_id
  loop
    -- Skip already-reversed statuses
    if v_item.status in ('Returned', 'Cancelled') then continue; end if;

    -- Cancel matching TRANSACTIONS Sale rows (most-recent first)
    -- For simplicity, mark them qty=0 (like Return marker)
    update transactions
      set qty = 0, revenue = 0, cost = 0, profit = 0
      where product = v_item.product and size = v_item.size and type = 'Sale' and qty > 0
        and id in (
          select id from transactions
          where product = v_item.product and size = v_item.size and type = 'Sale' and qty > 0
          order by date desc limit greatest(1, v_item.qty)
        );

    -- Restore INVENTORY.SOLD_*
    v_sold_col := case upper(v_item.size)
      when 'S'   then 'sold_s'   when 'M'   then 'sold_m'
      when 'L'   then 'sold_l'   when 'XL'  then 'sold_xl'
      when 'XXL' then 'sold_xxl' when '3XL' then 'sold_3xl'
      when 'ONE' then 'sold_m'   else null end;
    if v_sold_col is not null then
      execute format(
        'update inventory set %I = greatest(0, %I - $1), updated_at = now() where product = $2',
        v_sold_col, v_sold_col)
        using v_item.qty, v_item.product;
      v_stock := v_stock + v_item.qty;
    end if;
  end loop;

  -- Delete the Website_Orders rows
  delete from website_orders where order_id = p_order_id;
  get diagnostics v_rows = row_count;

  insert into audit_log (action, actor, details)
  values ('delete_website_order', p_user,
    jsonb_build_object('order_id', p_order_id, 'rows_deleted', v_rows, 'stock_restored', v_stock));
  return query select v_rows, v_stock;
end $$;

-- ---------------------------------------------------------------------
-- generate_monthly_report: aggregate orders/website_orders + tx + ad_tracker
-- (Fixes legacy bug: legacy code only counted ORDERS sheet, not Website_Orders)
-- ---------------------------------------------------------------------
create or replace function generate_monthly_report(p_year int, p_month int)
returns void language plpgsql security definer as $$
declare
  v_month_id text;
  v_revenue numeric(12,2);
  v_cost    numeric(12,2);
  v_ad      numeric(12,2);
  v_orders  int;
  v_net     numeric(12,2);
  v_start   timestamptz;
  v_end     timestamptz;
begin
  v_month_id := p_year || '-' || lpad(p_month::text, 2, '0');
  v_start := make_timestamptz(p_year, p_month, 1, 0, 0, 0, 'Asia/Dhaka');
  v_end   := v_start + interval '1 month';

  -- Revenue from manual ORDERS (not Cancelled/Returned)
  select coalesce(sum(total), 0) into v_revenue
    from orders
    where date >= v_start and date < v_end
      and status not in ('Cancelled', 'Returned');
  -- Add Website_Orders revenue
  select v_revenue + coalesce(sum(total), 0) into v_revenue
    from website_orders
    where date >= v_start and date < v_end
      and status not in ('Cancelled', 'Returned');

  -- Cost from TRANSACTIONS (type=Sale)
  select coalesce(sum(cost), 0) into v_cost
    from transactions
    where date >= v_start and date < v_end and type = 'Sale';

  -- AdSpend from AD_TRACKER
  select coalesce(sum(spend), 0) into v_ad
    from ad_tracker
    where date >= v_start and date < v_end;

  -- Order count
  select (select count(*) from orders where date >= v_start and date < v_end)
       + (select count(*) from website_orders where date >= v_start and date < v_end)
    into v_orders;

  v_net := v_revenue - v_cost - v_ad;

  insert into monthly_reports (month, revenue, cost, ad_spend, net_profit, orders)
  values (v_month_id, v_revenue, v_cost, v_ad, v_net, v_orders)
  on conflict (month) do update set
    revenue = excluded.revenue,
    cost = excluded.cost,
    ad_spend = excluded.ad_spend,
    net_profit = excluded.net_profit,
    orders = excluded.orders,
    updated_at = now();

  insert into audit_log (action, details)
  values ('generate_monthly_report', jsonb_build_object('month', v_month_id));
end $$;

-- ---------------------------------------------------------------------
-- steadfast_create_consignment: HTTP call to Steadfast (via Worker / Edge Function)
-- The actual HTTP call lives in the Worker (server-side); this RPC just
-- logs the consignment into steadfast_consignments.
-- This RPC is called by the Worker after the HTTP call returns.
-- ---------------------------------------------------------------------
create or replace function steadfast_log_consignment(
  p_consignment_id text, p_tracking_code text, p_invoice text,
  p_recipient_name text, p_recipient_phone text, p_recipient_address text,
  p_cod_amount numeric, p_total_lot int, p_item_description text, p_note text,
  p_delivery_type int default 0, p_stead_response jsonb default '{}'::jsonb
)
returns bigint language plpgsql security definer as $$
declare
  v_id bigint;
begin
  insert into steadfast_consignments
    (consignment_id, tracking_code, invoice, recipient_name, recipient_phone,
     recipient_address, cod_amount, total_lot, item_description, note,
     delivery_type, status, stead_response, last_checked_at)
  values
    (p_consignment_id, p_tracking_code, p_invoice, p_recipient_name, p_recipient_phone,
     p_recipient_address, p_cod_amount, p_total_lot, p_item_description, p_note,
     p_delivery_type, 'pending', p_stead_response, now())
  returning id into v_id;

  -- Update Website_Orders status to "Picked Up" + courier field
  update website_orders
    set status = 'Picked Up',
        courier = 'Steadfast' || case when p_tracking_code is not null then ' | ' || p_tracking_code else '' end,
        updated_at = now(),
        activity = coalesce(activity, '') || ' | Steadfast pickup created (' || coalesce(p_tracking_code, p_consignment_id) || ') @ ' || to_char(now() at time zone 'Asia/Dhaka', 'YYYY-MM-DD HH24:MI:SS')
    where order_id = p_invoice;

  insert into audit_log (action, details)
  values ('steadfast_create', jsonb_build_object('invoice', p_invoice, 'tracking_code', p_tracking_code));
  return v_id;
end $$;

-- ---------------------------------------------------------------------
-- fortress_block: upsert into blocked_devices
-- (Mirrors _fortressBlock in GAS line 5170)
-- ---------------------------------------------------------------------
create or replace function fortress_block(
  p_device_id text, p_blocked_by text default 'admin',
  p_reason text default 'manual', p_block_type text default 'hard',
  p_expires_at timestamptz default null, p_admin_notes text default null,
  p_order_attempts int default 0, p_risk_score int default 0,
  p_phones_seen text default null, p_ips_seen text default null
)
returns void language plpgsql security definer as $$
begin
  insert into blocked_devices
    (device_id, blocked_by, block_reason, block_type, expires_at, admin_notes,
     status, last_seen, order_attempts, risk_score, phones_seen, ips_seen)
  values
    (p_device_id, p_blocked_by, p_reason, p_block_type, p_expires_at, p_admin_notes,
     'active', now(), p_order_attempts, p_risk_score, p_phones_seen, p_ips_seen)
  on conflict (device_id) do update set
    blocked_by = excluded.blocked_by,
    block_reason = excluded.block_reason,
    block_type = excluded.block_type,
    expires_at = excluded.expires_at,
    admin_notes = excluded.admin_notes,
    status = 'active',
    last_seen = now(),
    order_attempts = excluded.order_attempts,
    risk_score = excluded.risk_score,
    phones_seen = excluded.phones_seen,
    ips_seen = excluded.ips_seen,
    updated_at = now();

  insert into fortress_log (log_id, event_type, device_id, risk_score, reason, actor)
  values (
    'FL-' || to_char(now() at time zone 'Asia/Dhaka', 'YYYYMMDD-HH24MISS') || '-' || upper(substring(md5(random()::text) for 6)),
    'block_added', p_device_id, p_risk_score, p_reason, p_blocked_by
  );

  insert into audit_log (action, details)
  values ('fortress_block', jsonb_build_object('device_id', p_device_id, 'reason', p_reason));
end $$;

-- ---------------------------------------------------------------------
-- fortress_unblock: delete from blocked_devices (soft delete: status='archived')
-- (Mirrors _fortressUnblock in GAS line 5231)
-- ---------------------------------------------------------------------
create or replace function fortress_unblock(p_device_id text, p_actor text default 'admin')
returns boolean language plpgsql security definer as $$
declare
  v_found boolean;
begin
  update blocked_devices
    set status = 'archived', updated_at = now()
    where device_id = p_device_id and status = 'active'
    returning true into v_found;

  if v_found then
    insert into fortress_log (log_id, event_type, device_id, reason, actor)
    values (
      'FL-' || to_char(now() at time zone 'Asia/Dhaka', 'YYYYMMDD-HH24MISS') || '-' || upper(substring(md5(random()::text) for 6)),
      'block_removed', p_device_id, 'admin_unblock', p_actor
    );
    insert into audit_log (action, details)
    values ('fortress_unblock', jsonb_build_object('device_id', p_device_id));
  end if;
  return coalesce(v_found, false);
end $$;

-- ---------------------------------------------------------------------
-- fortress_log_event: insert into fortress_log
-- ---------------------------------------------------------------------
create or replace function fortress_log_event(
  p_event_type text, p_device_id text default null, p_phone_hash text default null,
  p_ip text default null, p_country text default null, p_risk_score int default 0,
  p_reason text default null, p_actor text default 'auto',
  p_order_id text default null, p_notes text default null
)
returns text language plpgsql security definer as $$
declare
  v_log_id text;
begin
  v_log_id := 'FL-' || to_char(now() at time zone 'Asia/Dhaka', 'YYYYMMDD-HH24MISS')
              || '-' || upper(substring(md5(random()::text) for 6));
  insert into fortress_log
    (log_id, event_type, device_id, phone_hash, ip, country, risk_score, reason, actor, order_id, notes)
  values
    (v_log_id, p_event_type, p_device_id, p_phone_hash, p_ip, p_country, p_risk_score, p_reason, p_actor, p_order_id, p_notes);
  return v_log_id;
end $$;

-- ---------------------------------------------------------------------
-- fortress_lookup: return all active blocked + recent 100 log events
-- ---------------------------------------------------------------------
create or replace function fortress_lookup()
returns table (
  device_id text, blocked_at timestamptz, blocked_by text, block_reason text,
  block_type text, expires_at timestamptz, admin_notes text, status text,
  last_seen timestamptz, order_attempts int, risk_score int,
  phones_seen text, ips_seen text
) language plpgsql security definer as $$
begin
  return query
    select b.device_id, b.blocked_at, b.blocked_by, b.block_reason, b.block_type,
           b.expires_at, b.admin_notes, b.status, b.last_seen, b.order_attempts,
           b.risk_score, b.phones_seen, b.ips_seen
    from blocked_devices b
    where b.status = 'active'
    order by b.blocked_at desc;
end $$;

-- ---------------------------------------------------------------------
-- Helper: list recent fortress events (for admin UI)
-- ---------------------------------------------------------------------
create or replace function fortress_recent_events(p_limit int default 100)
returns table (
  log_id text, ts timestamptz, event_type text, device_id text, phone_hash text,
  ip text, country text, risk_score int, reason text, actor text,
  order_id text, notes text
) language plpgsql security definer as $$
begin
  return query
    select f.log_id, f.ts, f.event_type, f.device_id, f.phone_hash, f.ip, f.country,
           f.risk_score, f.reason, f.actor, f.order_id, f.notes
    from fortress_log f
    order by f.ts desc
    limit p_limit;
end $$;

-- ---------------------------------------------------------------------
-- Helper: get_steadfast_consignments (for admin UI)
-- ---------------------------------------------------------------------
create or replace function get_steadfast_consignments(p_invoice text default null)
returns table (
  id bigint, consignment_id text, tracking_code text, invoice text,
  recipient_name text, recipient_phone text, cod_amount numeric,
  total_lot int, status text, created_at timestamptz,
  last_checked_at timestamptz, delivered_at timestamptz
) language plpgsql security definer as $$
begin
  if p_invoice is not null then
    return query
      select s.id, s.consignment_id, s.tracking_code, s.invoice, s.recipient_name,
             s.recipient_phone, s.cod_amount, s.total_lot, s.status, s.created_at,
             s.last_checked_at, s.delivered_at
      from steadfast_consignments s
      where s.invoice = p_invoice
      order by s.created_at desc;
  else
    return query
      select s.id, s.consignment_id, s.tracking_code, s.invoice, s.recipient_name,
             s.recipient_phone, s.cod_amount, s.total_lot, s.status, s.created_at,
             s.last_checked_at, s.delivered_at
      from steadfast_consignments s
      order by s.created_at desc
      limit 200;
  end if;
end $$;

-- =====================================================================
-- pg_cron jobs (optional Ã¢â‚¬â€ set up after first deploy if available)
-- =====================================================================
-- Run at 1 AM Bangladesh time every day: cleanupOldOrders equivalent
-- (Remove comments + install via Supabase dashboard or psql if pg_cron enabled)
-- select cron.schedule('cleanup-old-orders', '0 1 * * *',
--   $$delete from website_orders where date < now() - interval '90 days'$$);
-- select cron.schedule('cleanup-expired-sessions', '0 2 * * *',
--   $$delete from admin_sessions where expires_at < now()$$);
-- select cron.schedule('refresh-customer-ltv', '0 3 * * *',
--   $$select update_customer_ltv()$$);

-- =====================================================================
-- END supplement.sql
-- =====================================================================

`; const m = monaco.editor.getModels(); m[0].setValue(sql); return { ok: true, len: sql.length, modelLen: m[0].getValue().length }; }